import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Box from '@mui/material/Box';
import CssBaseline from '@mui/material/CssBaseline';

import Header from '../components/header'
import Sidebar from '../components/sidebar'
import Toolbar from '@mui/material/Toolbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Box sx={{ display: 'flex' }}>
          <>
          <CssBaseline />
          <Header />
          <Sidebar />
          <Box component="main" sx={{ flexGrow: 1, p: 3 }}>
            <Toolbar />
            <>{children}</>
          </Box>
          </>
        </Box>
      </body>
    </html>
  )
}
